#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver 433610-web-01 100.25.134.4:80 check\n\tserver 433610-web-02 100.25.10.200:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
